//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1_Bitwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoNuevo
    {
        public int Id { get; set; }
        public string Dni { get; set; }
        public string Ciudad { get; set; }
        public string Nombre { get; set; }
        public string Domicilio { get; set; }
    }
}
